version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: pg_container
    restart: always
    environment:
      POSTGRES_USER: akshay
      POSTGRES_PASSWORD: letmein
      POSTGRES_DB: nexusdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./seat-booking-backend
    container_name: sbs_backend
    restart: always
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydb
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./seat-booking-front-end
    container_name: sbs_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata:
