version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: pg_container
    restart: always
    environment:
      POSTGRES_USER: akshay
      POSTGRES_PASSWORD: letmein
      POSTGRES_DB: nexusdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

  backend:
    build:
      context: ./seat-booking-backend
    container_name: sbs_backend
    restart: always
    environment:
      DATABASE_URL: postgres://akshay:letmein@postgres:5432/nexusdb
      NODE_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  pgdata:
